name: 'build'

on:
  push:
    branches:
    - master
jobs:
  build:
    name: 'Build'
    container: rguichard/xelatex
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build resume FR"
        run : |
          ls -l
          cd fr
          xelatex cv.tex
          cd ../en
          xelatex cv.tex
      - name: "Upload FR Scaleway Object Storage"
        uses: "quentinbrosse/scaleway-actions/object-storage@master"
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        with:
          args: "put --acl-public fr/cv.pdf s3://particule-resume/rgu/cv.fr.pdf"
      - name: "Upload EN Scaleway Object Storage"
        uses: "quentinbrosse/scaleway-actions/object-storage@master"
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        with:
          args: "put --acl-public en/cv.pdf s3://particule-resume/rgu/cv.en.pdf"
